<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7197dd0e-13d7-48e1-a506-a09d2de5776c</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
    <OpenApiGenerateDocumentsOnBuild>false</OpenApiGenerateDocumentsOnBuild>
    <OpenApiDocumentsDirectory>$(MSBuildThisFileDirectory)..\..\..</OpenApiDocumentsDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.1" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModernApp.Application\ModernApp.Application.csproj" />
    <ProjectReference Include="..\ModernApp.Infrastructure\ModernApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
